### ISSUE TITLE
A játék elején működik az exit menüpont, de később nem

### ISSUE THREAD

**Issue by Sonor7** [Sonor7/H-s-k#10]

**Comment by Honkee123** [comment]
Ez nem teljesen véletlen.
Teljesen más menüpontot használsz ott, ezért nem műkszik.
Ki debuggoltam neked, de ez nem lesz ingyé.
amikor az EnterMenu()-nut használod, akkor ott is meglehet adni neki bármit, de amikor kijön belőle baszik arra az értékre amit Te szeretnél.
Mert oké , hogy az EnterMenu() hívja a DisplayMenu, de amíg az első hívásnál a while figyeli hogy mit állítasz be, amikor már az Entermenu() hívod lófasz nem figyeli , hogy mit állítgaszt bent, és megy a feje után.
Ki is javítottam.
