### ISSUE TITLE
Random értékek a harc során

### ISSUE THREAD

**Issue by Sonor7** [Sonor7/H-s-k#8]
Minden körben generálódik egy szám, ami hozzáadódik a hitchance-hez.
Na most ez el is száll mint a győzelmi zászló, mert ugye intet nem lehet összeadni randommal, és randomot  nem lehet convertálni. (nem Iconvertable) ha berakom egy localhitchance változóba, akkor meg megáll mitn a kanál a levesben.

 jó mulatást :)

**Comment by Honkee123** [comment]
Ez a hiba még áll ?
Szerintem ezt már javítottam csak nem zártuk le.
Ha igen, légyszi pontosíts, mi a gond.
